version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env.dev

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: danareksa_dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./src/seeders/seed.sql:/docker-entrypoint-initdb.d/seed.sql
      # - ./test-reports:/usr/src/app/test-reports
      # - ./coverage:/usr/src/app/coverage

volumes:
  db_data: